// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for AllocationEntityType.
const (
	AllocationEntityTypeComputeInstance AllocationEntityType = "compute_instance"
	AllocationEntityTypePhysicalGpu     AllocationEntityType = "physical_gpu"
)

// Valid indicates whether the value is a known member of the AllocationEntityType enum.
func (e AllocationEntityType) Valid() bool {
	switch e {
	case AllocationEntityTypeComputeInstance:
		return true
	case AllocationEntityTypePhysicalGpu:
		return true
	default:
		return false
	}
}

// Defines values for AllocationState.
const (
	Allocated AllocationState = "allocated"
	Reserved  AllocationState = "reserved"
)

// Valid indicates whether the value is a known member of the AllocationState enum.
func (e AllocationState) Valid() bool {
	switch e {
	case Allocated:
		return true
	case Reserved:
		return true
	default:
		return false
	}
}

// Defines values for AttributionStatus.
const (
	AttributionStatusAvailable   AttributionStatus = "available"
	AttributionStatusStale       AttributionStatus = "stale"
	AttributionStatusUnavailable AttributionStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the AttributionStatus enum.
func (e AttributionStatus) Valid() bool {
	switch e {
	case AttributionStatusAvailable:
		return true
	case AttributionStatusStale:
		return true
	case AttributionStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for DiagnosticSeverity.
const (
	DiagnosticSeverityError   DiagnosticSeverity = "error"
	DiagnosticSeverityInfo    DiagnosticSeverity = "info"
	DiagnosticSeverityWarning DiagnosticSeverity = "warning"
)

// Valid indicates whether the value is a known member of the DiagnosticSeverity enum.
func (e DiagnosticSeverity) Valid() bool {
	switch e {
	case DiagnosticSeverityError:
		return true
	case DiagnosticSeverityInfo:
		return true
	case DiagnosticSeverityWarning:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for MetricScope.
const (
	MetricScopeComputeInstance MetricScope = "compute_instance"
	MetricScopeGpuInstance     MetricScope = "gpu_instance"
	MetricScopeHost            MetricScope = "host"
	MetricScopePhysicalGpu     MetricScope = "physical_gpu"
)

// Valid indicates whether the value is a known member of the MetricScope enum.
func (e MetricScope) Valid() bool {
	switch e {
	case MetricScopeComputeInstance:
		return true
	case MetricScopeGpuInstance:
		return true
	case MetricScopeHost:
		return true
	case MetricScopePhysicalGpu:
		return true
	default:
		return false
	}
}

// Defines values for MetricSource.
const (
	Dcgm      MetricSource = "dcgm"
	Nvml      MetricSource = "nvml"
	NvmlGpm   MetricSource = "nvml_gpm"
	Proc      MetricSource = "proc"
	Synthetic MetricSource = "synthetic"
)

// Valid indicates whether the value is a known member of the MetricSource enum.
func (e MetricSource) Valid() bool {
	switch e {
	case Dcgm:
		return true
	case Nvml:
		return true
	case NvmlGpm:
		return true
	case Proc:
		return true
	case Synthetic:
		return true
	default:
		return false
	}
}

// Defines values for MetricStatus.
const (
	MetricStatusAvailable        MetricStatus = "available"
	MetricStatusError            MetricStatus = "error"
	MetricStatusPermissionDenied MetricStatus = "permission_denied"
	MetricStatusStale            MetricStatus = "stale"
	MetricStatusUnsupported      MetricStatus = "unsupported"
)

// Valid indicates whether the value is a known member of the MetricStatus enum.
func (e MetricStatus) Valid() bool {
	switch e {
	case MetricStatusAvailable:
		return true
	case MetricStatusError:
		return true
	case MetricStatusPermissionDenied:
		return true
	case MetricStatusStale:
		return true
	case MetricStatusUnsupported:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeSettingsAllowedSamplingIntervalsMs.
const (
	RuntimeSettingsAllowedSamplingIntervalsMsN1000 RuntimeSettingsAllowedSamplingIntervalsMs = 1000
	RuntimeSettingsAllowedSamplingIntervalsMsN2000 RuntimeSettingsAllowedSamplingIntervalsMs = 2000
	RuntimeSettingsAllowedSamplingIntervalsMsN500  RuntimeSettingsAllowedSamplingIntervalsMs = 500
)

// Valid indicates whether the value is a known member of the RuntimeSettingsAllowedSamplingIntervalsMs enum.
func (e RuntimeSettingsAllowedSamplingIntervalsMs) Valid() bool {
	switch e {
	case RuntimeSettingsAllowedSamplingIntervalsMsN1000:
		return true
	case RuntimeSettingsAllowedSamplingIntervalsMsN2000:
		return true
	case RuntimeSettingsAllowedSamplingIntervalsMsN500:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeSettingsPatchSamplingIntervalMs.
const (
	RuntimeSettingsPatchSamplingIntervalMsN1000 RuntimeSettingsPatchSamplingIntervalMs = 1000
	RuntimeSettingsPatchSamplingIntervalMsN2000 RuntimeSettingsPatchSamplingIntervalMs = 2000
	RuntimeSettingsPatchSamplingIntervalMsN500  RuntimeSettingsPatchSamplingIntervalMs = 500
)

// Valid indicates whether the value is a known member of the RuntimeSettingsPatchSamplingIntervalMs enum.
func (e RuntimeSettingsPatchSamplingIntervalMs) Valid() bool {
	switch e {
	case RuntimeSettingsPatchSamplingIntervalMsN1000:
		return true
	case RuntimeSettingsPatchSamplingIntervalMsN2000:
		return true
	case RuntimeSettingsPatchSamplingIntervalMsN500:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotSchemaVersion.
const (
	V1 SnapshotSchemaVersion = "v1"
)

// Valid indicates whether the value is a known member of the SnapshotSchemaVersion enum.
func (e SnapshotSchemaVersion) Valid() bool {
	switch e {
	case V1:
		return true
	default:
		return false
	}
}

// Defines values for WorkloadKind.
const (
	Workspace WorkloadKind = "workspace"
)

// Valid indicates whether the value is a known member of the WorkloadKind enum.
func (e WorkloadKind) Valid() bool {
	switch e {
	case Workspace:
		return true
	default:
		return false
	}
}

// Defines values for WorkloadPlatform.
const (
	Coder WorkloadPlatform = "coder"
)

// Valid indicates whether the value is a known member of the WorkloadPlatform enum.
func (e WorkloadPlatform) Valid() bool {
	switch e {
	case Coder:
		return true
	default:
		return false
	}
}

// AlignedHistory defines model for AlignedHistory.
type AlignedHistory struct {
	Points []AlignedHistoryPoint            `json:"points"`
	Series []AlignedHistorySeriesDescriptor `json:"series"`
	Window string                           `json:"window"`
}

// AlignedHistoryPoint defines model for AlignedHistoryPoint.
type AlignedHistoryPoint struct {
	SampledAt time.Time `json:"sampledAt"`

	// Values Actual stored metric values keyed first by request series key. Missing values remain absent.
	Values map[string]map[string]float64 `json:"values"`
}

// AlignedHistoryRequest defines model for AlignedHistoryRequest.
type AlignedHistoryRequest struct {
	MaxPoints int                              `json:"maxPoints"`
	Series    []AlignedHistorySeriesDescriptor `json:"series"`

	// Window Positive Go duration no longer than configured retention. Windows over one hour return compact aggregate means.
	Window string `json:"window"`
}

// AlignedHistorySeriesDescriptor defines model for AlignedHistorySeriesDescriptor.
type AlignedHistorySeriesDescriptor struct {
	Entity  string   `json:"entity"`
	Key     string   `json:"key"`
	Metrics []string `json:"metrics"`
}

// AllocationEntityType defines model for AllocationEntityType.
type AllocationEntityType string

// AllocationState defines model for AllocationState.
type AllocationState string

// Attribution defines model for Attribution.
type Attribution struct {
	Assignments []ResourceAssignment  `json:"assignments"`
	ObservedAt  *time.Time            `json:"observedAt,omitempty"`
	Provider    string                `json:"provider"`
	Status      AttributionStatus     `json:"status"`
	Workloads   []WorkloadAttribution `json:"workloads"`
}

// AttributionStatus defines model for AttributionStatus.
type AttributionStatus string

// BuildInfo defines model for BuildInfo.
type BuildInfo struct {
	// BuildDate Build timestamp supplied by the linker.
	BuildDate string `json:"buildDate"`

	// Commit Source revision supplied by the linker.
	Commit string `json:"commit"`

	// Version Semantic version or dev for a development build.
	Version string `json:"version"`
}

// Capabilities defines model for Capabilities.
type Capabilities struct {
	Dcgm           ProviderState `json:"dcgm"`
	Gpm            ProviderState `json:"gpm"`
	Nvml           ProviderState `json:"nvml"`
	Proc           ProviderState `json:"proc"`
	ProfileMetrics bool          `json:"profileMetrics"`
}

// ComputeInstance defines model for ComputeInstance.
type ComputeInstance struct {
	Diagnostics *[]Diagnostic `json:"diagnostics,omitempty"`
	Generation  string        `json:"generation"`
	Id          uint32        `json:"id"`
	Memory      Memory        `json:"memory"`

	// Metrics Canonical metrics keyed by name. gpu_activity is time with any compute or graphics workload active; sm_activity is the percentage of SMs busy; pcie_rx_bytes_per_second and pcie_tx_bytes_per_second are PCIe bandwidth rates; power_limit is the enforced power ceiling in watts.
	Metrics MetricSet `json:"metrics"`
	Profile string    `json:"profile"`
	Uuid    string    `json:"uuid"`
}

// Diagnostic defines model for Diagnostic.
type Diagnostic struct {
	Code      string             `json:"code"`
	Component string             `json:"component"`
	Detail    *string            `json:"detail,omitempty"`
	Remedy    *string            `json:"remedy,omitempty"`
	Severity  DiagnosticSeverity `json:"severity"`
	Status    MetricStatus       `json:"status"`
	Summary   string             `json:"summary"`
}

// DiagnosticSeverity defines model for Diagnostic.Severity.
type DiagnosticSeverity string

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// GPU defines model for GPU.
type GPU struct {
	GpuInstances  []GpuInstance `json:"gpuInstances"`
	Index         int           `json:"index"`
	MaxMigDevices int           `json:"maxMigDevices"`
	Memory        Memory        `json:"memory"`

	// Metrics Canonical metrics keyed by name. gpu_activity is time with any compute or graphics workload active; sm_activity is the percentage of SMs busy; pcie_rx_bytes_per_second and pcie_tx_bytes_per_second are PCIe bandwidth rates; power_limit is the enforced power ceiling in watts.
	Metrics    MetricSet `json:"metrics"`
	MigEnabled bool      `json:"migEnabled"`
	Name       string    `json:"name"`
	PciBusId   *string   `json:"pciBusId,omitempty"`
	Uuid       string    `json:"uuid"`
}

// GpuInstance defines model for GpuInstance.
type GpuInstance struct {
	ComputeInstances []ComputeInstance `json:"computeInstances"`
	Generation       string            `json:"generation"`
	Id               uint32            `json:"id"`
	Memory           Memory            `json:"memory"`

	// Metrics Canonical metrics keyed by name. gpu_activity is time with any compute or graphics workload active; sm_activity is the percentage of SMs busy; pcie_rx_bytes_per_second and pcie_tx_bytes_per_second are PCIe bandwidth rates; power_limit is the enforced power ceiling in watts.
	Metrics MetricSet `json:"metrics"`
	Profile string    `json:"profile"`
	Uuid    string    `json:"uuid"`
}

// Health defines model for Health.
type Health struct {
	SampledAt time.Time    `json:"sampledAt"`
	Status    HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// HistoryPoint defines model for HistoryPoint.
type HistoryPoint struct {
	SampledAt time.Time          `json:"sampledAt"`
	Values    map[string]float32 `json:"values"`
}

// HistorySeries defines model for HistorySeries.
type HistorySeries struct {
	Entity  string         `json:"entity"`
	Metrics []string       `json:"metrics"`
	Points  []HistoryPoint `json:"points"`
	Window  string         `json:"window"`
}

// Host defines model for Host.
type Host struct {
	Arch     string `json:"arch"`
	Hostname string `json:"hostname"`
	Os       string `json:"os"`
}

// Memory defines model for Memory.
type Memory struct {
	FreeBytes  *uint64      `json:"freeBytes"`
	Message    *string      `json:"message,omitempty"`
	SampledAt  time.Time    `json:"sampledAt"`
	Scope      MetricScope  `json:"scope"`
	Source     MetricSource `json:"source"`
	Status     MetricStatus `json:"status"`
	TotalBytes *uint64      `json:"totalBytes"`
	UsedBytes  *uint64      `json:"usedBytes"`
}

// Metric defines model for Metric.
type Metric struct {
	Message   *string      `json:"message,omitempty"`
	SampledAt time.Time    `json:"sampledAt"`
	Scope     MetricScope  `json:"scope"`
	Source    MetricSource `json:"source"`
	Status    MetricStatus `json:"status"`
	Unit      string       `json:"unit"`
	Value     *float32     `json:"value"`
}

// MetricScope defines model for MetricScope.
type MetricScope string

// MetricSet Canonical metrics keyed by name. gpu_activity is time with any compute or graphics workload active; sm_activity is the percentage of SMs busy; pcie_rx_bytes_per_second and pcie_tx_bytes_per_second are PCIe bandwidth rates; power_limit is the enforced power ceiling in watts.
type MetricSet map[string]Metric

// MetricSource defines model for MetricSource.
type MetricSource string

// MetricStatus defines model for MetricStatus.
type MetricStatus string

// Process A GPU-connected process visible in Leviathan's current PID namespace. An open NVIDIA UVM handle includes idle CUDA contexts and does not imply active kernels, GPU memory use, or GI/CI ownership.
type Process struct {
	// CommandLine Present only when explicitly enabled.
	CommandLine *string `json:"commandLine,omitempty"`

	// Executable Resolved executable path
	Executable *string      `json:"executable,omitempty"`
	Message    *string      `json:"message,omitempty"`
	Pid        uint32       `json:"pid"`
	StartTime  *time.Time   `json:"startTime,omitempty"`
	Status     MetricStatus `json:"status"`
	User       *string      `json:"user,omitempty"`

	// WorkloadRef Opaque reference to a workload in this snapshot when optional attribution can resolve the process scope.
	WorkloadRef *string `json:"workloadRef,omitempty"`
}

// ProviderState defines model for ProviderState.
type ProviderState struct {
	Available bool         `json:"available"`
	Message   *string      `json:"message,omitempty"`
	Name      string       `json:"name"`
	Status    MetricStatus `json:"status"`
}

// ResourceAssignment A scheduler assignment; it does not prove active device use by a process.
type ResourceAssignment struct {
	EntityType  AllocationEntityType `json:"entityType"`
	EntityUuid  string               `json:"entityUuid"`
	State       AllocationState      `json:"state"`
	WorkloadRef string               `json:"workloadRef"`
}

// RuntimeSettings defines model for RuntimeSettings.
type RuntimeSettings struct {
	AllowedSamplingIntervalsMs []RuntimeSettingsAllowedSamplingIntervalsMs `json:"allowedSamplingIntervalsMs"`

	// HistoryWindowMs Maximum in-memory retention in milliseconds. The latest hour is raw; older data uses bounded compact trends.
	HistoryWindowMs int64 `json:"historyWindowMs"`

	// ProcessIntervalMs Effective GPU-process inventory refresh cadence in milliseconds.
	ProcessIntervalMs int64 `json:"processIntervalMs"`

	// ProfileIntervalMs Effective profile-metric refresh cadence in milliseconds.
	ProfileIntervalMs int64 `json:"profileIntervalMs"`

	// SamplingIntervalMs Effective process-local collector cadence in milliseconds.
	SamplingIntervalMs int64 `json:"samplingIntervalMs"`
}

// RuntimeSettingsAllowedSamplingIntervalsMs defines model for RuntimeSettings.AllowedSamplingIntervalsMs.
type RuntimeSettingsAllowedSamplingIntervalsMs int64

// RuntimeSettingsPatch defines model for RuntimeSettingsPatch.
type RuntimeSettingsPatch struct {
	SamplingIntervalMs RuntimeSettingsPatchSamplingIntervalMs `json:"samplingIntervalMs"`
}

// RuntimeSettingsPatchSamplingIntervalMs defines model for RuntimeSettingsPatch.SamplingIntervalMs.
type RuntimeSettingsPatchSamplingIntervalMs int64

// Snapshot defines model for Snapshot.
type Snapshot struct {
	Attribution  *Attribution `json:"attribution,omitempty"`
	Capabilities Capabilities `json:"capabilities"`
	Diagnostics  []Diagnostic `json:"diagnostics"`
	Gpus         []GPU        `json:"gpus"`
	Host         Host         `json:"host"`

	// Processes GPU-connected processes detected through open NVIDIA UVM device handles in the current PID namespace. Leviathan itself is excluded.
	Processes     []Process             `json:"processes"`
	SampledAt     time.Time             `json:"sampledAt"`
	SchemaVersion SnapshotSchemaVersion `json:"schemaVersion"`
	Sequence      uint64                `json:"sequence"`
}

// SnapshotSchemaVersion defines model for Snapshot.SchemaVersion.
type SnapshotSchemaVersion string

// WorkloadAttribution Sanitized workload display identity from an optional attribution source. The reference is opaque and source-scoped.
type WorkloadAttribution struct {
	Kind      WorkloadKind     `json:"kind"`
	Name      string           `json:"name"`
	OwnerName string           `json:"ownerName"`
	Platform  WorkloadPlatform `json:"platform"`
	Ref       string           `json:"ref"`
}

// WorkloadKind defines model for WorkloadKind.
type WorkloadKind string

// WorkloadPlatform defines model for WorkloadPlatform.
type WorkloadPlatform string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Unavailable defines model for Unavailable.
type Unavailable = Error

// GetHistoryParams defines parameters for GetHistory.
type GetHistoryParams struct {
	Entity string `form:"entity" json:"entity"`

	// Metrics Comma-separated canonical metric names.
	Metrics *string `form:"metrics,omitempty" json:"metrics,omitempty"`
	Window  *string `form:"window,omitempty" json:"window,omitempty"`

	// MaxPoints Maximum number of history points returned. Windows through one hour use raw samples; longer windows use deterministic compact means.
	MaxPoints *int `form:"maxPoints,omitempty" json:"maxPoints,omitempty"`
}

// GetAlignedHistoryJSONRequestBody defines body for GetAlignedHistory for application/json ContentType.
type GetAlignedHistoryJSONRequestBody = AlignedHistoryRequest

// UpdateRuntimeSettingsJSONRequestBody defines body for UpdateRuntimeSettings for application/json ContentType.
type UpdateRuntimeSettingsJSONRequestBody = RuntimeSettingsPatch
