// Package uplink provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package uplink

import (
	"time"
)

// Defines values for HealthStatus.
const (
	HealthDegraded    HealthStatus = "degraded"
	HealthOK          HealthStatus = "ok"
	HealthUnavailable HealthStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthDegraded:
		return true
	case HealthOK:
		return true
	case HealthUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for ReceiptStatus.
const (
	ReceiptAccepted ReceiptStatus = "accepted"
)

// Valid indicates whether the value is a known member of the ReceiptStatus enum.
func (e ReceiptStatus) Valid() bool {
	switch e {
	case ReceiptAccepted:
		return true
	default:
		return false
	}
}

// Defines values for SchemaVersion.
const (
	Schema SchemaVersion = "uplink-v1"
)

// Valid indicates whether the value is a known member of the SchemaVersion enum.
func (e SchemaVersion) Valid() bool {
	switch e {
	case Schema:
		return true
	default:
		return false
	}
}

// Agent defines model for Agent.
type Agent struct {
	BuildDate string `json:"buildDate"`
	Commit    string `json:"commit"`
	Version   string `json:"version"`
}

// CPU defines model for CPU.
type CPU struct {
	Load1             Metric       `json:"load1"`
	Load15            Metric       `json:"load15"`
	Load5             Metric       `json:"load5"`
	LogicalProcessors int          `json:"logicalProcessors"`
	Model             string       `json:"model"`
	SampledAt         time.Time    `json:"sampledAt"`
	Source            MetricSource `json:"source"`
	Status            MetricStatus `json:"status"`
	Utilization       Metric       `json:"utilization"`
}

// ComputeInstance defines model for ComputeInstance.
type ComputeInstance struct {
	ID      uint32    `json:"id"`
	Memory  Memory    `json:"memory"`
	Metrics MetricSet `json:"metrics"`
	Profile string    `json:"profile"`
	UUID    string    `json:"uuid"`
}

// DiagnosticCode defines model for DiagnosticCode.
type DiagnosticCode = string

// DiagnosticSeverity defines model for DiagnosticSeverity.
type DiagnosticSeverity = string

// DiagnosticSummary defines model for DiagnosticSummary.
type DiagnosticSummary = string

// DomainHealth defines model for DomainHealth.
type DomainHealth struct {
	SampledAt time.Time    `json:"sampledAt"`
	Status    HealthStatus `json:"status"`
}

// Envelope defines model for Envelope.
type Envelope struct {
	Agent     Agent         `json:"agent"`
	GPUs      []GPU         `json:"gpus"`
	Health    Health        `json:"health"`
	Host      Host          `json:"host"`
	SampledAt time.Time     `json:"sampledAt"`
	Schema    SchemaVersion `json:"schema"`
	Sequence  uint64        `json:"sequence"`
	StreamID  string        `json:"streamId"`
	System    System        `json:"system"`
}

// Filesystem defines model for Filesystem.
type Filesystem struct {
	AvailableBytes *uint64      `json:"availableBytes"`
	FSType         string       `json:"fsType"`
	ID             string       `json:"id"`
	MountPoint     string       `json:"mountPoint"`
	SampledAt      time.Time    `json:"sampledAt"`
	Scope          MetricScope  `json:"scope"`
	Source         MetricSource `json:"source"`
	Status         MetricStatus `json:"status"`
	TotalBytes     *uint64      `json:"totalBytes"`
	UsedBytes      *uint64      `json:"usedBytes"`
}

// GPU defines model for GPU.
type GPU struct {
	GPUInstances  []GPUInstance `json:"gpuInstances"`
	Index         int           `json:"index"`
	MaxMIGDevices int           `json:"maxMigDevices"`
	Memory        Memory        `json:"memory"`
	Metrics       MetricSet     `json:"metrics"`
	MIGEnabled    bool          `json:"migEnabled"`
	Name          string        `json:"name"`
	UUID          string        `json:"uuid"`
}

// GPUInstance defines model for GPUInstance.
type GPUInstance struct {
	ComputeInstances []ComputeInstance `json:"computeInstances"`
	ID               uint32            `json:"id"`
	Memory           Memory            `json:"memory"`
	Metrics          MetricSet         `json:"metrics"`
	Profile          string            `json:"profile"`
	UUID             string            `json:"uuid"`
}

// Health defines model for Health.
type Health struct {
	Diagnostics []SafeDiagnostic `json:"diagnostics"`
	GPU         DomainHealth     `json:"gpu"`
	Status      HealthStatus     `json:"status"`
	System      DomainHealth     `json:"system"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus string

// Host defines model for Host.
type Host struct {
	Arch     string `json:"arch"`
	Hostname string `json:"hostname"`
	OS       string `json:"os"`
}

// Memory defines model for Memory.
type Memory struct {
	AvailableBytes *uint64      `json:"availableBytes"`
	SampledAt      time.Time    `json:"sampledAt"`
	Scope          MetricScope  `json:"scope"`
	Source         MetricSource `json:"source"`
	Status         MetricStatus `json:"status"`
	TotalBytes     *uint64      `json:"totalBytes"`
	UsedBytes      *uint64      `json:"usedBytes"`
}

// Metric defines model for Metric.
type Metric struct {
	SampledAt time.Time    `json:"sampledAt"`
	Scope     MetricScope  `json:"scope"`
	Source    MetricSource `json:"source"`
	Status    MetricStatus `json:"status"`
	Unit      MetricUnit   `json:"unit"`
	Value     *float64     `json:"value"`
}

// MetricScope defines model for MetricScope.
type MetricScope = string

// MetricSet defines model for MetricSet.
type MetricSet map[string]Metric

// MetricSource defines model for MetricSource.
type MetricSource = string

// MetricStatus defines model for MetricStatus.
type MetricStatus = string

// MetricUnit defines model for MetricUnit.
type MetricUnit = string

// Receipt defines model for Receipt.
type Receipt struct {
	Sequence uint64        `json:"sequence"`
	Status   ReceiptStatus `json:"status"`
	StreamID string        `json:"streamId"`
}

// ReceiptStatus defines model for ReceiptStatus.
type ReceiptStatus string

// SafeDiagnostic defines model for SafeDiagnostic.
type SafeDiagnostic struct {
	Code     DiagnosticCode     `json:"code"`
	Severity DiagnosticSeverity `json:"severity"`
	Status   MetricStatus       `json:"status"`
	Summary  DiagnosticSummary  `json:"summary"`
}

// SchemaVersion defines model for SchemaVersion.
type SchemaVersion string

// Storage defines model for Storage.
type Storage struct {
	AvailableBytes      *uint64      `json:"availableBytes"`
	Filesystems         []Filesystem `json:"filesystems"`
	ReadBytesPerSecond  Metric       `json:"readBytesPerSecond"`
	SampledAt           time.Time    `json:"sampledAt"`
	Scope               MetricScope  `json:"scope"`
	Source              MetricSource `json:"source"`
	Status              MetricStatus `json:"status"`
	TotalBytes          *uint64      `json:"totalBytes"`
	UsedBytes           *uint64      `json:"usedBytes"`
	WriteBytesPerSecond Metric       `json:"writeBytesPerSecond"`
}

// System defines model for System.
type System struct {
	CPU       CPU          `json:"cpu"`
	Memory    SystemMemory `json:"memory"`
	SampledAt time.Time    `json:"sampledAt"`
	Status    MetricStatus `json:"status"`
	Storage   Storage      `json:"storage"`
}

// SystemMemory defines model for SystemMemory.
type SystemMemory struct {
	AvailableBytes *uint64      `json:"availableBytes"`
	SampledAt      time.Time    `json:"sampledAt"`
	Scope          MetricScope  `json:"scope"`
	Source         MetricSource `json:"source"`
	Status         MetricStatus `json:"status"`
	TotalBytes     *uint64      `json:"totalBytes"`
	UsedBytes      *uint64      `json:"usedBytes"`
	Utilization    Metric       `json:"utilization"`
}

// Rejected defines model for Rejected.
type Rejected struct {
	Error string `json:"error"`
}

// PutUplinkV1SnapshotJSONRequestBody defines body for PutUplinkV1Snapshot for application/json ContentType.
type PutUplinkV1SnapshotJSONRequestBody = Envelope
