/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the latest immutable host snapshot. */
        get: operations["getSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return retained metrics for one entity UUID. */
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/aligned": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Return multiple retained metric series on one shared timestamp set. */
        post: operations["getAlignedHistory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream snapshot and runtime-settings server-sent events. */
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return telemetry and local GPU-process capabilities. */
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return effective process-local runtime settings. */
        get: operations["getRuntimeSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change the process-local collector sampling interval. */
        patch: operations["updateRuntimeSettings"];
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return build metadata for the running MIGLens binary. */
        get: operations["getBuildInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report whether a snapshot is available. */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        MetricStatus: "available" | "unsupported" | "permission_denied" | "stale" | "error";
        /** @enum {string} */
        MetricSource: "nvml" | "nvml_gpm" | "dcgm" | "proc" | "synthetic";
        /** @enum {string} */
        MetricScope: "host" | "physical_gpu" | "gpu_instance" | "compute_instance";
        Metric: {
            value: number | null;
            unit: string;
            source: components["schemas"]["MetricSource"];
            scope: components["schemas"]["MetricScope"];
            /** Format: date-time */
            sampledAt: string;
            status: components["schemas"]["MetricStatus"];
            message?: string;
        };
        /** @description Canonical metrics keyed by name. gpu_activity is time with any compute or graphics workload active; sm_activity is the percentage of SMs busy; pcie_rx_bytes_per_second and pcie_tx_bytes_per_second are PCIe bandwidth rates; power_limit is the enforced power ceiling in watts. */
        MetricSet: {
            [key: string]: components["schemas"]["Metric"];
        };
        Memory: {
            /** Format: uint64 */
            totalBytes: number | null;
            /** Format: uint64 */
            usedBytes: number | null;
            /** Format: uint64 */
            freeBytes: number | null;
            source: components["schemas"]["MetricSource"];
            scope: components["schemas"]["MetricScope"];
            /** Format: date-time */
            sampledAt: string;
            status: components["schemas"]["MetricStatus"];
            message?: string;
        };
        /** @description A GPU-connected process visible in MIGLens' current PID namespace. An open NVIDIA UVM handle includes idle CUDA contexts and does not imply active kernels, GPU memory use, or GI/CI ownership. */
        Process: {
            /** Format: uint32 */
            pid: number;
            user?: string;
            /** @description Resolved executable path */
            executable?: string;
            /** @description Present only when explicitly enabled. */
            commandLine?: string;
            /** Format: date-time */
            startTime?: string;
            status: components["schemas"]["MetricStatus"];
            message?: string;
        };
        /** @enum {string} */
        WorkloadPlatform: "coder";
        /** @enum {string} */
        WorkloadKind: "workspace";
        /** @enum {string} */
        AllocationEntityType: "physical_gpu" | "compute_instance";
        /** @enum {string} */
        AllocationState: "allocated" | "reserved";
        /** @description Sanitized workload display identity from an optional attribution source. The reference is opaque and source-scoped. */
        WorkloadAttribution: {
            ref: string;
            platform: components["schemas"]["WorkloadPlatform"];
            kind: components["schemas"]["WorkloadKind"];
            name: string;
            ownerName: string;
        };
        /** @description A scheduler assignment; it does not prove active device use by a process. */
        ResourceAssignment: {
            workloadRef: string;
            entityType: components["schemas"]["AllocationEntityType"];
            entityUuid: string;
            state: components["schemas"]["AllocationState"];
        };
        /** @enum {string} */
        AttributionStatus: "available" | "stale" | "unavailable";
        Attribution: {
            provider: string;
            status: components["schemas"]["AttributionStatus"];
            /** Format: date-time */
            observedAt?: string;
            workloads: components["schemas"]["WorkloadAttribution"][];
            assignments: components["schemas"]["ResourceAssignment"][];
        };
        ComputeInstance: {
            uuid: string;
            /** Format: uint32 */
            id: number;
            profile: string;
            memory: components["schemas"]["Memory"];
            metrics: components["schemas"]["MetricSet"];
            generation: string;
            diagnostics?: components["schemas"]["Diagnostic"][];
        };
        GpuInstance: {
            uuid: string;
            /** Format: uint32 */
            id: number;
            profile: string;
            generation: string;
            memory: components["schemas"]["Memory"];
            metrics: components["schemas"]["MetricSet"];
            computeInstances: components["schemas"]["ComputeInstance"][];
        };
        GPU: {
            uuid: string;
            index: number;
            name: string;
            pciBusId?: string;
            migEnabled: boolean;
            maxMigDevices: number;
            memory: components["schemas"]["Memory"];
            metrics: components["schemas"]["MetricSet"];
            gpuInstances: components["schemas"]["GpuInstance"][];
        };
        ProviderState: {
            name: string;
            available: boolean;
            status: components["schemas"]["MetricStatus"];
            message?: string;
        };
        Capabilities: {
            nvml: components["schemas"]["ProviderState"];
            gpm: components["schemas"]["ProviderState"];
            dcgm: components["schemas"]["ProviderState"];
            proc: components["schemas"]["ProviderState"];
            profileMetrics: boolean;
        };
        RuntimeSettings: {
            /**
             * Format: int64
             * @description Effective process-local collector cadence in milliseconds.
             */
            samplingIntervalMs: number;
            /**
             * Format: int64
             * @description Effective profile-metric refresh cadence in milliseconds.
             */
            profileIntervalMs: number;
            /**
             * Format: int64
             * @description Effective GPU-process inventory refresh cadence in milliseconds.
             */
            processIntervalMs: number;
            /**
             * Format: int64
             * @description Maximum in-memory retention in milliseconds.
             */
            historyWindowMs: number;
            allowedSamplingIntervalsMs: (500 | 1000 | 2000)[];
        };
        RuntimeSettingsPatch: {
            /**
             * Format: int64
             * @enum {integer}
             */
            samplingIntervalMs: 500 | 1000 | 2000;
        };
        BuildInfo: {
            /** @description Semantic version or dev for a development build. */
            version: string;
            /** @description Source revision supplied by the linker. */
            commit: string;
            /** @description Build timestamp supplied by the linker. */
            buildDate: string;
        };
        Diagnostic: {
            code: string;
            /** @enum {string} */
            severity: "info" | "warning" | "error";
            component: string;
            summary: string;
            detail?: string;
            remedy?: string;
            status: components["schemas"]["MetricStatus"];
        };
        Host: {
            hostname: string;
            os: string;
            arch: string;
        };
        Snapshot: {
            /** @constant */
            schemaVersion: "v1";
            /** Format: uint64 */
            sequence: number;
            /** Format: date-time */
            sampledAt: string;
            host: components["schemas"]["Host"];
            gpus: components["schemas"]["GPU"][];
            /** @description GPU-connected processes detected through open NVIDIA UVM device handles in the current PID namespace. MIGLens itself is excluded. */
            processes: components["schemas"]["Process"][];
            attribution?: components["schemas"]["Attribution"];
            capabilities: components["schemas"]["Capabilities"];
            diagnostics: components["schemas"]["Diagnostic"][];
        };
        HistoryPoint: {
            /** Format: date-time */
            sampledAt: string;
            values: {
                [key: string]: number;
            };
        };
        HistorySeries: {
            entity: string;
            metrics: string[];
            window: string;
            points: components["schemas"]["HistoryPoint"][];
        };
        AlignedHistorySeriesDescriptor: {
            key: string;
            entity: string;
            metrics: string[];
        };
        AlignedHistoryRequest: {
            /** @description Positive Go duration no longer than the configured history retention. */
            window: string;
            maxPoints: number;
            series: components["schemas"]["AlignedHistorySeriesDescriptor"][];
        };
        AlignedHistoryPoint: {
            /** Format: date-time */
            sampledAt: string;
            /** @description Actual stored metric values keyed first by request series key. Missing values remain absent. */
            values: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        AlignedHistory: {
            window: string;
            series: components["schemas"]["AlignedHistorySeriesDescriptor"][];
            points: components["schemas"]["AlignedHistoryPoint"][];
        };
        Health: {
            /** @constant */
            status: "ok";
            /** Format: date-time */
            sampledAt: string;
        };
        Error: {
            error: string;
        };
    };
    responses: {
        /** @description Invalid request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A live snapshot is not available. */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    getHistory: {
        parameters: {
            query: {
                entity: string;
                /** @description Comma-separated canonical metric names. */
                metrics?: string;
                window?: string;
                /** @description Maximum number of history points returned after shape-preserving downsampling. */
                maxPoints?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded in-memory series. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistorySeries"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getAlignedHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlignedHistoryRequest"];
            };
        };
        responses: {
            /** @description Shape-preserving aligned in-memory history with no interpolated values. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlignedHistory"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description The request body is not JSON. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A stream of snapshot and settings events. Clients should reconnect using standard SSE semantics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider capabilities. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
    getRuntimeSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Effective runtime settings and dashboard sampling choices. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeSettings"];
                };
            };
        };
    };
    updateRuntimeSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuntimeSettingsPatch"];
            };
        };
        responses: {
            /** @description Effective runtime settings after the update. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeSettings"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description The mutation body is not JSON. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getBuildInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable build metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildInfo"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
}
